In [1]:
import pandas as pd
import requests
from pathlib import Path

In [5]:
project_root = Path.cwd().parent

raw_path = r"C:\Users\chand\Downloads\mutual_fund_analytics\data\raw"

print("Raw Data Folder:", raw_path)

Raw Data Folder: C:\Users\chand\Downloads\mutual_fund_analytics\data\raw

In [7]:
fund_master = pd.read_csv(r"C:\Users\chand\Downloads\mutual_fund_analytics\data\raw\01_fund_master.csv")
nav_history = pd.read_csv(r"C:\Users\chand\Downloads\mutual_fund_analytics\data\raw\02_nav_history.csv")
aum = pd.read_csv(r"C:\Users\chand\Downloads\mutual_fund_analytics\data\raw\03_aum_by_fund_house.csv")
sip = pd.read_csv(r"C:\Users\chand\Downloads\mutual_fund_analytics\data\raw\04_monthly_sip_inflows.csv")
category = pd.read_csv(r"C:\Users\chand\Downloads\mutual_fund_analytics\data\raw\05_category_inflows.csv")
folio = pd.read_csv(r"C:\Users\chand\Downloads\mutual_fund_analytics\data\raw\06_industry_folio_count.csv")
performance = pd.read_csv(r"C:\Users\chand\Downloads\mutual_fund_analytics\data\raw\07_scheme_performance.csv")
transactions = pd.read_csv(r"C:\Users\chand\Downloads\mutual_fund_analytics\data\raw\08_investor_transactions.csv")
portfolio = pd.read_csv(r"C:\Users\chand\Downloads\mutual_fund_analytics\data\raw\09_portfolio_holdings.csv")
benchmark = pd.read_csv(r"C:\Users\chand\Downloads\mutual_fund_analytics\data\raw\10_benchmark_indices.csv")

In [9]:
datasets = {
    "Fund Master": fund_master,
    "NAV History": nav_history,
    "AUM": aum,
    "SIP": sip,
    "Category": category,
    "Folio": folio,
    "Performance": performance,
    "Transactions": transactions,
    "Portfolio": portfolio,
    "Benchmark": benchmark,
}

for name, df in datasets.items():
    print("="*50)
    print(name)
    print("Rows:", df.shape[0])
    print("Columns:", df.shape[1])

==================================================
Fund Master
Rows: 40
Columns: 15
==================================================
NAV History
Rows: 42219
Columns: 3
==================================================
AUM
Rows: 90
Columns: 5
==================================================
SIP
Rows: 48
Columns: 6
==================================================
Category
Rows: 144
Columns: 3
==================================================
Folio
Rows: 21
Columns: 6
==================================================
Performance
Rows: 40
Columns: 19
==================================================
Transactions
Rows: 32778
Columns: 13
==================================================
Portfolio
Rows: 322
Columns: 8
==================================================
Benchmark
Rows: 8050
Columns: 3

In [11]:
fund_master.head()

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

In [13]:
nav_history.head()

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

In [15]:
performance.head()

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

In [17]:
transactions.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [19]:
schemes = {
    "SBI_Bluechip": 119551,
    "ICICI_Bluechip": 120503,
    "Nippon_LargeCap": 118632,
    "Axis_Bluechip": 119092,
    "Kotak_Bluechip": 120841
}

In [27]:
for name, code in schemes.items():

    url = f"https://api.mfapi.in/mf/{code}"

    response = requests.get(url)

    if response.status_code == 200:

        data = response.json()

        history = pd.DataFrame(data["data"])

        history["amfi_code"] = code

        history.to_csv(
            r"C:\Users\chand\Downloads\mutual_fund_analytics\data\raw\f"{name}_nav.csv",
            index=False
        )

        print(f"{name} downloaded successfully.")

    else:

        print(f"Unable to download {name}")

SyntaxError: unterminated string literal (detected at line 16) (2890942926.py, line 16)